version: '3.9'

services:
  statistics:
    container_name: gdagil-labs
    image: danil2286/cg-streamlit:latest
    # build:
    #   context: ./app
    #   dockerfile: Dockerfile
    restart: always
    ports: 
      - 8080:8080